# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HopeApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HopeApp

  target 'HopeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HopeAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Kingfisher', '3.1.1'
pod 'Alamofire', '4.0.1'
end
